// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuKpK13fVWYsNilZqLfNpgTGrzVWVbGA',
    appId: '1:515717897547:android:919b13bb8061ddbe1ddcce',
    messagingSenderId: '515717897547',
    projectId: 'ai-powered-shopping',
    storageBucket: 'ai-powered-shopping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv73F7hUaHTtYzIkauj1flyqDF7Wn-iT4',
    appId: '1:515717897547:ios:d4627743072a426a1ddcce',
    messagingSenderId: '515717897547',
    projectId: 'ai-powered-shopping',
    storageBucket: 'ai-powered-shopping.firebasestorage.app',
    iosBundleId: 'com.example.aiPoweredShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFK1jHy2DO3Wme2gG181dH-kvOyC-tNTM',
    appId: '1:515717897547:web:e830f0eb577dcb491ddcce',
    messagingSenderId: '515717897547',
    projectId: 'ai-powered-shopping',
    authDomain: 'ai-powered-shopping.firebaseapp.com',
    storageBucket: 'ai-powered-shopping.firebasestorage.app',
    measurementId: 'G-90N917PK3L',
  );

}